export const AuditAction = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  WAREHOUSE_CREATED: 'WAREHOUSE_CREATED',
  WAREHOUSE_UPDATED: 'WAREHOUSE_UPDATED',
  STOCK_RECEIVED: 'STOCK_RECEIVED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  SALES_ORDER_CREATED: 'SALES_ORDER_CREATED',
  SALES_ORDER_CONFIRMED: 'SALES_ORDER_CONFIRMED',
  SALES_ORDER_CANCELLED: 'SALES_ORDER_CANCELLED',
  SALES_ORDER_FULFILLED: 'SALES_ORDER_FULFILLED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  SALES_ORDER_COMPLETED: 'SALES_ORDER_COMPLETED',
} as const;

export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction];
